/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "secondary": "#006e2d",
        "on-secondary": "#ffffff",
        "secondary-container": "#7cf994",
        "on-secondary-container": "#007230",
        "tertiary": "#6a1edb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8343f4",
        "on-tertiary-container": "#f7edff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#faf8ff",
        "on-surface": "#191b23",
        "on-surface-variant": "#434655",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "surface-container": "#ededf9",
        "surface-container-high": "#e7e7f3",
        "surface-container-highest": "#e1e2ed",
        "surface-dim": "#d9d9e5",
        "surface-bright": "#faf8ff",
        "surface-tint": "#0053db",
        "surface-variant": "#e1e2ed",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#f0f0fb",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "background": "#faf8ff",
        "on-background": "#191b23",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#7ffc97",
        "secondary-fixed-dim": "#62df7d",
        "on-secondary-fixed": "#002109",
        "on-secondary-fixed-variant": "#005320",
        "tertiary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed": "#25005a",
        "on-tertiary-fixed-variant": "#5a00c6",
      },
      fontSize: {
        "h1":         ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "700" }],
        "h2":         ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
        "metric-lg":  ["32px", { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" }],
        "body-md":    ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm":    ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "id-mono":    ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      fontFamily: {
        "h1": ["DM Sans", "sans-serif"],
        "h2": ["DM Sans", "sans-serif"],
        "metric-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "label-caps": ["DM Sans", "sans-serif"],
        "id-mono": ["DM Mono", "monospace"]
      },
      spacing: {
        "xs": "4px", "sm": "8px", "md": "16px",
        "lg": "24px", "xl": "32px",
        "gutter": "16px", "container-padding": "24px", "unit": "4px"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      }
    },
  },
  plugins: [],
}
